name: Update
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
    - name: Install R dependencies
      run: |
        install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s",
                         .Platform$pkgType, R.Version()$os, R.Version()$arch))
        pak::pkg_install(c("data.table", "reticulate", "glue"))
      shell: Rscript {0}
    - name: Update
      run: |
        Rscript update.R
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs
        git diff-index --quiet HEAD || git commit -m "update docs"
        git push
