name: Update
on:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: 'release'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install stackapi
    - name: Install R dependencies
      run: |
        install.packages(c("data.table", "reticulate", "glue"))
      shell: Rscript {0}
    - name: Update
      run: |
        ./update.R
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs
        git diff-index --quiet HEAD || git commit -m "update docs"
        git push
